# 对空格的要求十分高
# 可以注入到配置中，可以给实体类赋值
server: {port: 8080}
# pets: [aa,bb,cc]



# 数据库配置
#更换环境
spring:
  mail:
    username: 972950811@qq.com
    password: yhtjjwmnitmebeif
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable:
              true
  profiles:
    active: test
  thymeleaf:
    cache: false  
#关闭模板引擎的缓存
#配置自定义实体类
myperson: 
  name: ${random.uuid}
  age: ${random.int}
  sex: false